FROM ros:jazzy-ros-base

# Install rosbridge-suite
RUN apt-get update && apt-get install -y \
    ros-jazzy-rosbridge-suite \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy python dummy node script
COPY nodes_stress_test.py .
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
