services:
  n8n:
    build:
      context: .
      dockerfile: docker/n8n/Dockerfile
      args:
        - N8N_IMAGE=n8n-local-context

    network_mode: host
    volumes:
      - n8n_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 970

    environment:
      - N8N_USER_FOLDER=/data
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_AUTH_TOKEN=supersecrettoken
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_NATIVE_PYTHON_RUNNER=true
      - N8N_DEV_RELOAD=true
  runner:
    build:
      context: .
      dockerfile: docker/runner/Dockerfile

    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://172.0.0.1:5679
      - N8N_RUNNERS_AUTH_TOKEN=supersecrettoken
    network_mode: host
    volumes:
      - n8n_data:/data
    depends_on:
      - n8n

volumes:
  n8n_data:
